# Generated by Django 4.1.2 on 2022-10-20 08:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=255)),
                ('answer', models.CharField(default='', max_length=255)),
                ('choice', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), default=list, size=5)),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='book.book')),
            ],
        ),
    ]
