# Generated by Django 4.1.2 on 2022-10-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(default='', max_length=255)),
                ('Answer', models.CharField(default='', max_length=255)),
                ('Choice', models.CharField(default='', max_length=255)),
                ('BookID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
