# Generated by Django 4.1.2 on 2022-10-29 10:13

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('question', models.CharField(default='', max_length=255)),
                ('answer', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('choice', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), blank=True, default=list, size=5)),
                ('hint', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(default=0), default=list, size=2)),
                ('content', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='book.content')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('content', 'quiz_number'), name='content_quiz_number'),
        ),
    ]
