# Generated by Django 4.1.2 on 2022-10-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hint',
            field=models.TextField(default=''),
        ),
    ]
