# Generated by Django 4.1.2 on 2022-10-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
