# Generated by Django 4.1.2 on 2022-10-20 08:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='choice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), blank=True, default=list, size=5),
        ),
    ]
