# Generated by Django 4.1.2 on 2022-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_quiz_number_alter_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('book', 'quiz_number'), name='book_quiz_number'),
        ),
    ]
