# Generated by Django 4.1.2 on 2022-10-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_chapter_quiz_book_quiz_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='type',
        ),
    ]
