# Generated by Django 4.1.2 on 2022-10-25 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_number',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
