# Generated by Django 4.1.2 on 2022-10-27 06:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_content_book_chapter_and_more'),
        ('quiz', '0007_alter_quiz_answer_alter_quiz_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='book_quiz_number',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='book',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='chapter',
        ),
        migrations.AddField(
            model_name='quiz',
            name='content',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='book.content'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hint',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(default=0), default=list, size=2),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('content', 'quiz_number'), name='content_quiz_number'),
        ),
    ]
