# Generated by Django 4.1.2 on 2022-10-20 08:10

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('format', models.CharField(blank=True, max_length=45)),
                ('keyword', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=45), default=list, size=5)),
                ('page', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('complete', models.BooleanField(default=False)),
                ('bookmark', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='book.book')),
            ],
            options={
                'unique_together': {('author', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('textID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contents', serialize=False, to='report.bookreport')),
                ('original', models.TextField()),
                ('correct', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
