# Generated by Django 4.1.2 on 2022-10-11 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('TextID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Original', models.TextField()),
                ('Correct', models.TextField()),
                ('Feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Step', models.SmallIntegerField(default=0)),
                ('Format', models.SmallIntegerField(default=0)),
                ('Keyword', models.TextField(null=True)),
                ('Page', models.SmallIntegerField(default=0)),
                ('Complete', models.BooleanField(default=False)),
                ('Bookmark', models.BooleanField(default=False)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('BookID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('TextID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.text')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('UserID', 'BookID')},
            },
        ),
    ]
