# Generated by Django 4.1.2 on 2022-10-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='format',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
