# Generated by Django 4.1.2 on 2022-10-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='report',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.text'),
        ),
    ]
