# Generated by Django 4.1.2 on 2022-10-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreport',
            name='TextID',
        ),
        migrations.AlterField(
            model_name='text',
            name='TextID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='report.bookreport'),
        ),
    ]
