# Generated by Django 4.1.2 on 2022-10-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('book', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='BookID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='Bookmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='Format',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='Keyword',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='Page',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='Step',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='TextID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='report.text'),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='UserID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
