# Generated by Django 4.1.2 on 2022-10-11 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_bookid_alter_book_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_remove_bookreport_textid_alter_text_textid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreport',
            old_name='UserID',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='bookreport',
            old_name='BookID',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='bookreport',
            unique_together={('Author', 'book')},
        ),
    ]
