# Generated by Django 4.1.2 on 2022-10-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_activity_report'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activity',
            name='report_chapter',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='report',
        ),
    ]
