# Generated by Django 4.1.2 on 2022-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_bookreport_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='format',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='keyword',
            field=models.TextField(blank=True),
        ),
    ]
