# Generated by Django 4.1.2 on 2022-10-25 07:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_bookreport_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='keyword',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=45), blank=True, default=list, size=5), blank=True, default=list, size=None),
        ),
    ]
