# Generated by Django 4.1.2 on 2022-10-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('book', '0001_initial'),
        ('report', '0002_alter_bookreport_bookid_alter_bookreport_bookmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='BookID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='TextID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='report.text'),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='UserID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
