# Generated by Django 4.1.2 on 2022-10-29 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_activity_report_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='report.text'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('text', 'chapter'), name='text_chapter'),
        ),
    ]
