# Generated by Django 4.1.2 on 2022-10-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_bookid'),
        ('accounts', '0002_alter_user_userid'),
        ('report', '0003_alter_bookreport_bookid_alter_bookreport_textid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='BookID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='TextID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.text'),
        ),
        migrations.AlterField(
            model_name='bookreport',
            name='UserID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='text',
            name='TextID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
