# Generated by Django 4.1.2 on 2022-10-25 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_bookreport_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreport',
            name='quiz_score',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
