# Generated by Django 4.1.2 on 2022-10-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_activity_text_activity_text_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='textID',
            new_name='report',
        ),
    ]
