# Generated by Django 4.1.2 on 2022-10-29 13:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_textid_text_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='question_set',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=3),
        ),
        migrations.AlterField(
            model_name='activity',
            name='feeling',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
