# Generated by Django 4.1.2 on 2022-11-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_activity_question_set_alter_activity_feeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreport',
            name='curr_chapter',
            field=models.SmallIntegerField(default=1),
        ),
    ]
