# Generated by Django 4.1.3 on 2022-11-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_bookreport_curr_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreport',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
