# Generated by Django 4.1.3 on 2022-11-29 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_bookreport_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreport',
            name='step',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
