# Generated by Django 4.1.2 on 2022-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PassWord', models.CharField(max_length=255)),
                ('Nickname', models.CharField(max_length=45)),
                ('Ability', models.IntegerField()),
            ],
        ),
    ]
