# Generated by Django 4.1.2 on 2022-10-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=45)),
                ('Contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('TextID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Original', models.TextField()),
                ('Correct', models.TextField()),
                ('Feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PassWord', models.CharField(max_length=255)),
                ('Nickname', models.CharField(max_length=45)),
                ('Ability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.book')),
                ('Question', models.CharField(max_length=255)),
                ('Answer', models.CharField(max_length=255)),
                ('Choice', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookReport',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('Step', models.SmallIntegerField()),
                ('Format', models.SmallIntegerField()),
                ('Keyword', models.TextField()),
                ('Page', models.SmallIntegerField()),
                ('Complete', models.BooleanField()),
                ('Bookmark', models.BooleanField()),
                ('Time', models.DateTimeField(auto_now=True)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.book')),
                ('TextID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.text')),
            ],
            options={
                'unique_together': {('UserID', 'BookID')},
            },
        ),
    ]
