# Generated by Django 4.1.2 on 2022-11-09 11:32

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]), default=[0, 0, 0, 0, 0], size=5),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.SmallIntegerField(default=0),
        ),
    ]
