# Generated by Django 4.1.3 on 2022-11-10 16:12

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_genres_user_introduction_user_name_user_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]), default=[0, 0, 0, 0, 0], size=5),
        ),
    ]
