# Generated by Django 4.1.2 on 2022-10-11 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Ability',
        ),
        migrations.AddField(
            model_name='ability',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
