# Generated by Django 4.1.3 on 2022-12-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_nickname_alter_user_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessories',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.CharField(default='', max_length=255),
        ),
    ]
