# Generated by Django 4.1.3 on 2022-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_accessories_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accessories',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
