# Generated by Django 4.1.3 on 2022-12-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_accessories_alter_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accessories',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
