# Generated by Django 4.1.2 on 2022-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=45)),
                ('contents', models.TextField()),
            ],
        ),
    ]
