# Generated by Django 4.1.2 on 2022-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=45)),
                ('Contents', models.TextField()),
            ],
        ),
    ]
