# Generated by Django 4.1.2 on 2022-10-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookID',
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
