# Generated by Django 4.1.2 on 2022-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
