# Generated by Django 4.1.2 on 2022-10-25 07:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_total_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_pages',
            new_name='total_chapters',
        ),
        migrations.RemoveField(
            model_name='book',
            name='contents',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.SmallIntegerField(default=0)),
                ('content', models.TextField()),
                ('sentences', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('lines', models.SmallIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='book.book')),
            ],
        ),
    ]
