# Generated by Django 4.1.2 on 2022-10-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_total_pages_book_total_chapters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='content',
            name='sentences',
        ),
    ]
