# Generated by Django 4.1.2 on 2022-10-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_content_lines_remove_content_sentences'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('book', 'chapter'), name='book_chapter'),
        ),
    ]
