# Generated by Django 4.1.2 on 2022-10-27 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_content_book_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_lines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='content',
            name='pages',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
