# Generated by Django 4.1.2 on 2022-10-27 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_content_content_lines_content_pages'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='content',
            name='book_chapter',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_chapters',
        ),
        migrations.AddField(
            model_name='book',
            name='chapters',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='content',
            name='quizzes',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_lines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('book', 'chapter'), name='book_chapter'),
        ),
    ]
